/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package music_advisor;

import music_advisor.view.App;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {

    }
}
